# Auto-generated by create_ppt_slides.py
# Run from repo root: .\scripts\create_ppt_slides_run.ps1
Write-Host 'Creating slide 1/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_1.json
Write-Host 'Creating slide 2/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_2.json
Write-Host 'Creating slide 3/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_3.json
Write-Host 'Creating slide 4/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_4.json
Write-Host 'Creating slide 5/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_5.json
Write-Host 'Creating slide 6/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_6.json
Write-Host 'Creating slide 7/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_7.json
Write-Host 'Creating slide 8/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_8.json
Write-Host 'Creating slide 9/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_9.json
Write-Host 'Creating slide 10/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_10.json
Write-Host 'Creating slide 11/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_11.json
Write-Host 'Creating slide 12/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_12.json
Write-Host 'Creating slide 13/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_13.json
Write-Host 'Creating slide 14/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_14.json
Write-Host 'Creating slide 15/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_15.json
Write-Host 'Creating slide 16/16 ...'
npx lark-cli slides xml_presentation.slide create --as user --params @scripts/ppt_params.json --data @scripts/ppt_payload_16.json
Write-Host 'All slides created.'